/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// AttributeApplyConfiguration represents an declarative configuration of the Attribute type for use
// with apply.
type AttributeApplyConfiguration struct {
	Name                             *string `json:"name,omitempty"`
	AttributeValueApplyConfiguration `json:",inline"`
}

// AttributeApplyConfiguration constructs an declarative configuration of the Attribute type for use with
// apply.
func Attribute() *AttributeApplyConfiguration {
	return &AttributeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithName(value string) *AttributeApplyConfiguration {
	b.Name = &value
	return b
}

// WithQuantityValue sets the QuantityValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuantityValue field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithQuantityValue(value resource.Quantity) *AttributeApplyConfiguration {
	b.QuantityValue = &value
	return b
}

// WithBoolValue sets the BoolValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BoolValue field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithBoolValue(value bool) *AttributeApplyConfiguration {
	b.BoolValue = &value
	return b
}

// WithIntValue sets the IntValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IntValue field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithIntValue(value int64) *AttributeApplyConfiguration {
	b.IntValue = &value
	return b
}

// WithIntSliceValue sets the IntSliceValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IntSliceValue field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithIntSliceValue(value *Int64SliceApplyConfiguration) *AttributeApplyConfiguration {
	b.IntSliceValue = value
	return b
}

// WithStringValue sets the StringValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StringValue field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithStringValue(value string) *AttributeApplyConfiguration {
	b.StringValue = &value
	return b
}

// WithStringSliceValue sets the StringSliceValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StringSliceValue field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithStringSliceValue(value *StringSliceApplyConfiguration) *AttributeApplyConfiguration {
	b.StringSliceValue = value
	return b
}
