/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "k8s.io/api/storage/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	scheme "k8s.io/client-go/kubernetes/scheme"
	rest "k8s.io/client-go/rest"
)

// CSIStoragePoolsGetter has a method to return a CSIStoragePoolInterface.
// A group's client should implement this interface.
type CSIStoragePoolsGetter interface {
	CSIStoragePools() CSIStoragePoolInterface
}

// CSIStoragePoolInterface has methods to work with CSIStoragePool resources.
type CSIStoragePoolInterface interface {
	Create(*v1alpha1.CSIStoragePool) (*v1alpha1.CSIStoragePool, error)
	Update(*v1alpha1.CSIStoragePool) (*v1alpha1.CSIStoragePool, error)
	UpdateStatus(*v1alpha1.CSIStoragePool) (*v1alpha1.CSIStoragePool, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CSIStoragePool, error)
	List(opts v1.ListOptions) (*v1alpha1.CSIStoragePoolList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSIStoragePool, err error)
	CSIStoragePoolExpansion
}

// cSIStoragePools implements CSIStoragePoolInterface
type cSIStoragePools struct {
	client rest.Interface
}

// newCSIStoragePools returns a CSIStoragePools
func newCSIStoragePools(c *StorageV1alpha1Client) *cSIStoragePools {
	return &cSIStoragePools{
		client: c.RESTClient(),
	}
}

// Get takes name of the cSIStoragePool, and returns the corresponding cSIStoragePool object, and an error if there is any.
func (c *cSIStoragePools) Get(name string, options v1.GetOptions) (result *v1alpha1.CSIStoragePool, err error) {
	result = &v1alpha1.CSIStoragePool{}
	err = c.client.Get().
		Resource("csistoragepools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CSIStoragePools that match those selectors.
func (c *cSIStoragePools) List(opts v1.ListOptions) (result *v1alpha1.CSIStoragePoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CSIStoragePoolList{}
	err = c.client.Get().
		Resource("csistoragepools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cSIStoragePools.
func (c *cSIStoragePools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("csistoragepools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cSIStoragePool and creates it.  Returns the server's representation of the cSIStoragePool, and an error, if there is any.
func (c *cSIStoragePools) Create(cSIStoragePool *v1alpha1.CSIStoragePool) (result *v1alpha1.CSIStoragePool, err error) {
	result = &v1alpha1.CSIStoragePool{}
	err = c.client.Post().
		Resource("csistoragepools").
		Body(cSIStoragePool).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cSIStoragePool and updates it. Returns the server's representation of the cSIStoragePool, and an error, if there is any.
func (c *cSIStoragePools) Update(cSIStoragePool *v1alpha1.CSIStoragePool) (result *v1alpha1.CSIStoragePool, err error) {
	result = &v1alpha1.CSIStoragePool{}
	err = c.client.Put().
		Resource("csistoragepools").
		Name(cSIStoragePool.Name).
		Body(cSIStoragePool).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cSIStoragePools) UpdateStatus(cSIStoragePool *v1alpha1.CSIStoragePool) (result *v1alpha1.CSIStoragePool, err error) {
	result = &v1alpha1.CSIStoragePool{}
	err = c.client.Put().
		Resource("csistoragepools").
		Name(cSIStoragePool.Name).
		SubResource("status").
		Body(cSIStoragePool).
		Do().
		Into(result)
	return
}

// Delete takes name of the cSIStoragePool and deletes it. Returns an error if one occurs.
func (c *cSIStoragePools) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("csistoragepools").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cSIStoragePools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("csistoragepools").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cSIStoragePool.
func (c *cSIStoragePools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSIStoragePool, err error) {
	result = &v1alpha1.CSIStoragePool{}
	err = c.client.Patch(pt).
		Resource("csistoragepools").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
