/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "k8s.io/api/storage/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	scheme "k8s.io/client-go/kubernetes/scheme"
	rest "k8s.io/client-go/rest"
)

// CSIStoragesGetter has a method to return a CSIStorageInterface.
// A group's client should implement this interface.
type CSIStoragesGetter interface {
	CSIStorages() CSIStorageInterface
}

// CSIStorageInterface has methods to work with CSIStorage resources.
type CSIStorageInterface interface {
	Create(*v1alpha1.CSIStorage) (*v1alpha1.CSIStorage, error)
	Update(*v1alpha1.CSIStorage) (*v1alpha1.CSIStorage, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CSIStorage, error)
	List(opts v1.ListOptions) (*v1alpha1.CSIStorageList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSIStorage, err error)
	CSIStorageExpansion
}

// cSIStorages implements CSIStorageInterface
type cSIStorages struct {
	client rest.Interface
}

// newCSIStorages returns a CSIStorages
func newCSIStorages(c *StorageV1alpha1Client) *cSIStorages {
	return &cSIStorages{
		client: c.RESTClient(),
	}
}

// Get takes name of the cSIStorage, and returns the corresponding cSIStorage object, and an error if there is any.
func (c *cSIStorages) Get(name string, options v1.GetOptions) (result *v1alpha1.CSIStorage, err error) {
	result = &v1alpha1.CSIStorage{}
	err = c.client.Get().
		Resource("csistorages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CSIStorages that match those selectors.
func (c *cSIStorages) List(opts v1.ListOptions) (result *v1alpha1.CSIStorageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CSIStorageList{}
	err = c.client.Get().
		Resource("csistorages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cSIStorages.
func (c *cSIStorages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("csistorages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cSIStorage and creates it.  Returns the server's representation of the cSIStorage, and an error, if there is any.
func (c *cSIStorages) Create(cSIStorage *v1alpha1.CSIStorage) (result *v1alpha1.CSIStorage, err error) {
	result = &v1alpha1.CSIStorage{}
	err = c.client.Post().
		Resource("csistorages").
		Body(cSIStorage).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cSIStorage and updates it. Returns the server's representation of the cSIStorage, and an error, if there is any.
func (c *cSIStorages) Update(cSIStorage *v1alpha1.CSIStorage) (result *v1alpha1.CSIStorage, err error) {
	result = &v1alpha1.CSIStorage{}
	err = c.client.Put().
		Resource("csistorages").
		Name(cSIStorage.Name).
		Body(cSIStorage).
		Do().
		Into(result)
	return
}

// Delete takes name of the cSIStorage and deletes it. Returns an error if one occurs.
func (c *cSIStorages) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("csistorages").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cSIStorages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("csistorages").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cSIStorage.
func (c *cSIStorages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSIStorage, err error) {
	result = &v1alpha1.CSIStorage{}
	err = c.client.Patch(pt).
		Resource("csistorages").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
