/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha2 "k8s.io/api/resource/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	resourcev1alpha2 "k8s.io/client-go/applyconfigurations/resource/v1alpha2"
	testing "k8s.io/client-go/testing"
)

// FakeNodeResourceCapacities implements NodeResourceCapacityInterface
type FakeNodeResourceCapacities struct {
	Fake *FakeResourceV1alpha2
}

var noderesourcecapacitiesResource = v1alpha2.SchemeGroupVersion.WithResource("noderesourcecapacities")

var noderesourcecapacitiesKind = v1alpha2.SchemeGroupVersion.WithKind("NodeResourceCapacity")

// Get takes name of the nodeResourceCapacity, and returns the corresponding nodeResourceCapacity object, and an error if there is any.
func (c *FakeNodeResourceCapacities) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(noderesourcecapacitiesResource, name), &v1alpha2.NodeResourceCapacity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NodeResourceCapacity), err
}

// List takes label and field selectors, and returns the list of NodeResourceCapacities that match those selectors.
func (c *FakeNodeResourceCapacities) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.NodeResourceCapacityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(noderesourcecapacitiesResource, noderesourcecapacitiesKind, opts), &v1alpha2.NodeResourceCapacityList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.NodeResourceCapacityList{ListMeta: obj.(*v1alpha2.NodeResourceCapacityList).ListMeta}
	for _, item := range obj.(*v1alpha2.NodeResourceCapacityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeResourceCapacities.
func (c *FakeNodeResourceCapacities) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(noderesourcecapacitiesResource, opts))
}

// Create takes the representation of a nodeResourceCapacity and creates it.  Returns the server's representation of the nodeResourceCapacity, and an error, if there is any.
func (c *FakeNodeResourceCapacities) Create(ctx context.Context, nodeResourceCapacity *v1alpha2.NodeResourceCapacity, opts v1.CreateOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(noderesourcecapacitiesResource, nodeResourceCapacity), &v1alpha2.NodeResourceCapacity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NodeResourceCapacity), err
}

// Update takes the representation of a nodeResourceCapacity and updates it. Returns the server's representation of the nodeResourceCapacity, and an error, if there is any.
func (c *FakeNodeResourceCapacities) Update(ctx context.Context, nodeResourceCapacity *v1alpha2.NodeResourceCapacity, opts v1.UpdateOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(noderesourcecapacitiesResource, nodeResourceCapacity), &v1alpha2.NodeResourceCapacity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NodeResourceCapacity), err
}

// Delete takes name of the nodeResourceCapacity and deletes it. Returns an error if one occurs.
func (c *FakeNodeResourceCapacities) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(noderesourcecapacitiesResource, name, opts), &v1alpha2.NodeResourceCapacity{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeResourceCapacities) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(noderesourcecapacitiesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.NodeResourceCapacityList{})
	return err
}

// Patch applies the patch and returns the patched nodeResourceCapacity.
func (c *FakeNodeResourceCapacities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.NodeResourceCapacity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(noderesourcecapacitiesResource, name, pt, data, subresources...), &v1alpha2.NodeResourceCapacity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NodeResourceCapacity), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeResourceCapacity.
func (c *FakeNodeResourceCapacities) Apply(ctx context.Context, nodeResourceCapacity *resourcev1alpha2.NodeResourceCapacityApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	if nodeResourceCapacity == nil {
		return nil, fmt.Errorf("nodeResourceCapacity provided to Apply must not be nil")
	}
	data, err := json.Marshal(nodeResourceCapacity)
	if err != nil {
		return nil, err
	}
	name := nodeResourceCapacity.Name
	if name == nil {
		return nil, fmt.Errorf("nodeResourceCapacity.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(noderesourcecapacitiesResource, *name, types.ApplyPatchType, data), &v1alpha2.NodeResourceCapacity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NodeResourceCapacity), err
}
