/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "k8s.io/api/storage/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCSIStoragePools implements CSIStoragePoolInterface
type FakeCSIStoragePools struct {
	Fake *FakeStorageV1alpha1
}

var csistoragepoolsResource = schema.GroupVersionResource{Group: "storage.k8s.io", Version: "v1alpha1", Resource: "csistoragepools"}

var csistoragepoolsKind = schema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1alpha1", Kind: "CSIStoragePool"}

// Get takes name of the cSIStoragePool, and returns the corresponding cSIStoragePool object, and an error if there is any.
func (c *FakeCSIStoragePools) Get(name string, options v1.GetOptions) (result *v1alpha1.CSIStoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(csistoragepoolsResource, name), &v1alpha1.CSIStoragePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSIStoragePool), err
}

// List takes label and field selectors, and returns the list of CSIStoragePools that match those selectors.
func (c *FakeCSIStoragePools) List(opts v1.ListOptions) (result *v1alpha1.CSIStoragePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(csistoragepoolsResource, csistoragepoolsKind, opts), &v1alpha1.CSIStoragePoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CSIStoragePoolList{ListMeta: obj.(*v1alpha1.CSIStoragePoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.CSIStoragePoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cSIStoragePools.
func (c *FakeCSIStoragePools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(csistoragepoolsResource, opts))
}

// Create takes the representation of a cSIStoragePool and creates it.  Returns the server's representation of the cSIStoragePool, and an error, if there is any.
func (c *FakeCSIStoragePools) Create(cSIStoragePool *v1alpha1.CSIStoragePool) (result *v1alpha1.CSIStoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(csistoragepoolsResource, cSIStoragePool), &v1alpha1.CSIStoragePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSIStoragePool), err
}

// Update takes the representation of a cSIStoragePool and updates it. Returns the server's representation of the cSIStoragePool, and an error, if there is any.
func (c *FakeCSIStoragePools) Update(cSIStoragePool *v1alpha1.CSIStoragePool) (result *v1alpha1.CSIStoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(csistoragepoolsResource, cSIStoragePool), &v1alpha1.CSIStoragePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSIStoragePool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCSIStoragePools) UpdateStatus(cSIStoragePool *v1alpha1.CSIStoragePool) (*v1alpha1.CSIStoragePool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(csistoragepoolsResource, "status", cSIStoragePool), &v1alpha1.CSIStoragePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSIStoragePool), err
}

// Delete takes name of the cSIStoragePool and deletes it. Returns an error if one occurs.
func (c *FakeCSIStoragePools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(csistoragepoolsResource, name), &v1alpha1.CSIStoragePool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCSIStoragePools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(csistoragepoolsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CSIStoragePoolList{})
	return err
}

// Patch applies the patch and returns the patched cSIStoragePool.
func (c *FakeCSIStoragePools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSIStoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(csistoragepoolsResource, name, pt, data, subresources...), &v1alpha1.CSIStoragePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSIStoragePool), err
}
