//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha1 "k8s.io/api/resource/structured/namedresources/v1alpha1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	namedresources "k8s.io/kubernetes/pkg/apis/resource/structured/namedresources"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AllocatedInstance)(nil), (*namedresources.AllocatedInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AllocatedInstance_To_namedresources_AllocatedInstance(a.(*v1alpha1.AllocatedInstance), b.(*namedresources.AllocatedInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.AllocatedInstance)(nil), (*v1alpha1.AllocatedInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_AllocatedInstance_To_v1alpha1_AllocatedInstance(a.(*namedresources.AllocatedInstance), b.(*v1alpha1.AllocatedInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AllocationResult)(nil), (*namedresources.AllocationResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AllocationResult_To_namedresources_AllocationResult(a.(*v1alpha1.AllocationResult), b.(*namedresources.AllocationResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.AllocationResult)(nil), (*v1alpha1.AllocationResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_AllocationResult_To_v1alpha1_AllocationResult(a.(*namedresources.AllocationResult), b.(*v1alpha1.AllocationResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Attribute)(nil), (*namedresources.Attribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Attribute_To_namedresources_Attribute(a.(*v1alpha1.Attribute), b.(*namedresources.Attribute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.Attribute)(nil), (*v1alpha1.Attribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_Attribute_To_v1alpha1_Attribute(a.(*namedresources.Attribute), b.(*v1alpha1.Attribute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AttributeValue)(nil), (*namedresources.AttributeValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AttributeValue_To_namedresources_AttributeValue(a.(*v1alpha1.AttributeValue), b.(*namedresources.AttributeValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.AttributeValue)(nil), (*v1alpha1.AttributeValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_AttributeValue_To_v1alpha1_AttributeValue(a.(*namedresources.AttributeValue), b.(*v1alpha1.AttributeValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Filter)(nil), (*namedresources.Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Filter_To_namedresources_Filter(a.(*v1alpha1.Filter), b.(*namedresources.Filter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.Filter)(nil), (*v1alpha1.Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_Filter_To_v1alpha1_Filter(a.(*namedresources.Filter), b.(*v1alpha1.Filter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Instance)(nil), (*namedresources.Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Instance_To_namedresources_Instance(a.(*v1alpha1.Instance), b.(*namedresources.Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.Instance)(nil), (*v1alpha1.Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_Instance_To_v1alpha1_Instance(a.(*namedresources.Instance), b.(*v1alpha1.Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Request)(nil), (*namedresources.Request)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Request_To_namedresources_Request(a.(*v1alpha1.Request), b.(*namedresources.Request), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.Request)(nil), (*v1alpha1.Request)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_Request_To_v1alpha1_Request(a.(*namedresources.Request), b.(*v1alpha1.Request), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Resources)(nil), (*namedresources.Resources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Resources_To_namedresources_Resources(a.(*v1alpha1.Resources), b.(*namedresources.Resources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.Resources)(nil), (*v1alpha1.Resources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_Resources_To_v1alpha1_Resources(a.(*namedresources.Resources), b.(*v1alpha1.Resources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StringSlice)(nil), (*namedresources.StringSlice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StringSlice_To_namedresources_StringSlice(a.(*v1alpha1.StringSlice), b.(*namedresources.StringSlice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*namedresources.StringSlice)(nil), (*v1alpha1.StringSlice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_namedresources_StringSlice_To_v1alpha1_StringSlice(a.(*namedresources.StringSlice), b.(*v1alpha1.StringSlice), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AllocatedInstance_To_namedresources_AllocatedInstance(in *v1alpha1.AllocatedInstance, out *namedresources.AllocatedInstance, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_AllocatedInstance_To_namedresources_AllocatedInstance is an autogenerated conversion function.
func Convert_v1alpha1_AllocatedInstance_To_namedresources_AllocatedInstance(in *v1alpha1.AllocatedInstance, out *namedresources.AllocatedInstance, s conversion.Scope) error {
	return autoConvert_v1alpha1_AllocatedInstance_To_namedresources_AllocatedInstance(in, out, s)
}

func autoConvert_namedresources_AllocatedInstance_To_v1alpha1_AllocatedInstance(in *namedresources.AllocatedInstance, out *v1alpha1.AllocatedInstance, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_namedresources_AllocatedInstance_To_v1alpha1_AllocatedInstance is an autogenerated conversion function.
func Convert_namedresources_AllocatedInstance_To_v1alpha1_AllocatedInstance(in *namedresources.AllocatedInstance, out *v1alpha1.AllocatedInstance, s conversion.Scope) error {
	return autoConvert_namedresources_AllocatedInstance_To_v1alpha1_AllocatedInstance(in, out, s)
}

func autoConvert_v1alpha1_AllocationResult_To_namedresources_AllocationResult(in *v1alpha1.AllocationResult, out *namedresources.AllocationResult, s conversion.Scope) error {
	out.Instances = *(*[]namedresources.AllocatedInstance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_v1alpha1_AllocationResult_To_namedresources_AllocationResult is an autogenerated conversion function.
func Convert_v1alpha1_AllocationResult_To_namedresources_AllocationResult(in *v1alpha1.AllocationResult, out *namedresources.AllocationResult, s conversion.Scope) error {
	return autoConvert_v1alpha1_AllocationResult_To_namedresources_AllocationResult(in, out, s)
}

func autoConvert_namedresources_AllocationResult_To_v1alpha1_AllocationResult(in *namedresources.AllocationResult, out *v1alpha1.AllocationResult, s conversion.Scope) error {
	out.Instances = *(*[]v1alpha1.AllocatedInstance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_namedresources_AllocationResult_To_v1alpha1_AllocationResult is an autogenerated conversion function.
func Convert_namedresources_AllocationResult_To_v1alpha1_AllocationResult(in *namedresources.AllocationResult, out *v1alpha1.AllocationResult, s conversion.Scope) error {
	return autoConvert_namedresources_AllocationResult_To_v1alpha1_AllocationResult(in, out, s)
}

func autoConvert_v1alpha1_Attribute_To_namedresources_Attribute(in *v1alpha1.Attribute, out *namedresources.Attribute, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_AttributeValue_To_namedresources_AttributeValue(&in.AttributeValue, &out.AttributeValue, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Attribute_To_namedresources_Attribute is an autogenerated conversion function.
func Convert_v1alpha1_Attribute_To_namedresources_Attribute(in *v1alpha1.Attribute, out *namedresources.Attribute, s conversion.Scope) error {
	return autoConvert_v1alpha1_Attribute_To_namedresources_Attribute(in, out, s)
}

func autoConvert_namedresources_Attribute_To_v1alpha1_Attribute(in *namedresources.Attribute, out *v1alpha1.Attribute, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_namedresources_AttributeValue_To_v1alpha1_AttributeValue(&in.AttributeValue, &out.AttributeValue, s); err != nil {
		return err
	}
	return nil
}

// Convert_namedresources_Attribute_To_v1alpha1_Attribute is an autogenerated conversion function.
func Convert_namedresources_Attribute_To_v1alpha1_Attribute(in *namedresources.Attribute, out *v1alpha1.Attribute, s conversion.Scope) error {
	return autoConvert_namedresources_Attribute_To_v1alpha1_Attribute(in, out, s)
}

func autoConvert_v1alpha1_AttributeValue_To_namedresources_AttributeValue(in *v1alpha1.AttributeValue, out *namedresources.AttributeValue, s conversion.Scope) error {
	out.QuantityValue = (*resource.Quantity)(unsafe.Pointer(in.QuantityValue))
	out.BoolValue = (*bool)(unsafe.Pointer(in.BoolValue))
	out.IntValue = (*int64)(unsafe.Pointer(in.IntValue))
	out.IntSliceValue = (*namedresources.IntSlice)(unsafe.Pointer(in.IntSliceValue))
	out.StringValue = (*string)(unsafe.Pointer(in.StringValue))
	out.StringSliceValue = (*namedresources.StringSlice)(unsafe.Pointer(in.StringSliceValue))
	return nil
}

// Convert_v1alpha1_AttributeValue_To_namedresources_AttributeValue is an autogenerated conversion function.
func Convert_v1alpha1_AttributeValue_To_namedresources_AttributeValue(in *v1alpha1.AttributeValue, out *namedresources.AttributeValue, s conversion.Scope) error {
	return autoConvert_v1alpha1_AttributeValue_To_namedresources_AttributeValue(in, out, s)
}

func autoConvert_namedresources_AttributeValue_To_v1alpha1_AttributeValue(in *namedresources.AttributeValue, out *v1alpha1.AttributeValue, s conversion.Scope) error {
	out.QuantityValue = (*resource.Quantity)(unsafe.Pointer(in.QuantityValue))
	out.BoolValue = (*bool)(unsafe.Pointer(in.BoolValue))
	out.IntValue = (*int64)(unsafe.Pointer(in.IntValue))
	out.IntSliceValue = (*v1alpha1.Int64Slice)(unsafe.Pointer(in.IntSliceValue))
	out.StringValue = (*string)(unsafe.Pointer(in.StringValue))
	out.StringSliceValue = (*v1alpha1.StringSlice)(unsafe.Pointer(in.StringSliceValue))
	return nil
}

// Convert_namedresources_AttributeValue_To_v1alpha1_AttributeValue is an autogenerated conversion function.
func Convert_namedresources_AttributeValue_To_v1alpha1_AttributeValue(in *namedresources.AttributeValue, out *v1alpha1.AttributeValue, s conversion.Scope) error {
	return autoConvert_namedresources_AttributeValue_To_v1alpha1_AttributeValue(in, out, s)
}

func autoConvert_v1alpha1_Filter_To_namedresources_Filter(in *v1alpha1.Filter, out *namedresources.Filter, s conversion.Scope) error {
	out.Selector = in.Selector
	return nil
}

// Convert_v1alpha1_Filter_To_namedresources_Filter is an autogenerated conversion function.
func Convert_v1alpha1_Filter_To_namedresources_Filter(in *v1alpha1.Filter, out *namedresources.Filter, s conversion.Scope) error {
	return autoConvert_v1alpha1_Filter_To_namedresources_Filter(in, out, s)
}

func autoConvert_namedresources_Filter_To_v1alpha1_Filter(in *namedresources.Filter, out *v1alpha1.Filter, s conversion.Scope) error {
	out.Selector = in.Selector
	return nil
}

// Convert_namedresources_Filter_To_v1alpha1_Filter is an autogenerated conversion function.
func Convert_namedresources_Filter_To_v1alpha1_Filter(in *namedresources.Filter, out *v1alpha1.Filter, s conversion.Scope) error {
	return autoConvert_namedresources_Filter_To_v1alpha1_Filter(in, out, s)
}

func autoConvert_v1alpha1_Instance_To_namedresources_Instance(in *v1alpha1.Instance, out *namedresources.Instance, s conversion.Scope) error {
	out.Name = in.Name
	out.Attributes = *(*[]namedresources.Attribute)(unsafe.Pointer(&in.Attributes))
	return nil
}

// Convert_v1alpha1_Instance_To_namedresources_Instance is an autogenerated conversion function.
func Convert_v1alpha1_Instance_To_namedresources_Instance(in *v1alpha1.Instance, out *namedresources.Instance, s conversion.Scope) error {
	return autoConvert_v1alpha1_Instance_To_namedresources_Instance(in, out, s)
}

func autoConvert_namedresources_Instance_To_v1alpha1_Instance(in *namedresources.Instance, out *v1alpha1.Instance, s conversion.Scope) error {
	out.Name = in.Name
	out.Attributes = *(*[]v1alpha1.Attribute)(unsafe.Pointer(&in.Attributes))
	return nil
}

// Convert_namedresources_Instance_To_v1alpha1_Instance is an autogenerated conversion function.
func Convert_namedresources_Instance_To_v1alpha1_Instance(in *namedresources.Instance, out *v1alpha1.Instance, s conversion.Scope) error {
	return autoConvert_namedresources_Instance_To_v1alpha1_Instance(in, out, s)
}

func autoConvert_v1alpha1_Request_To_namedresources_Request(in *v1alpha1.Request, out *namedresources.Request, s conversion.Scope) error {
	out.Selector = in.Selector
	return nil
}

// Convert_v1alpha1_Request_To_namedresources_Request is an autogenerated conversion function.
func Convert_v1alpha1_Request_To_namedresources_Request(in *v1alpha1.Request, out *namedresources.Request, s conversion.Scope) error {
	return autoConvert_v1alpha1_Request_To_namedresources_Request(in, out, s)
}

func autoConvert_namedresources_Request_To_v1alpha1_Request(in *namedresources.Request, out *v1alpha1.Request, s conversion.Scope) error {
	out.Selector = in.Selector
	return nil
}

// Convert_namedresources_Request_To_v1alpha1_Request is an autogenerated conversion function.
func Convert_namedresources_Request_To_v1alpha1_Request(in *namedresources.Request, out *v1alpha1.Request, s conversion.Scope) error {
	return autoConvert_namedresources_Request_To_v1alpha1_Request(in, out, s)
}

func autoConvert_v1alpha1_Resources_To_namedresources_Resources(in *v1alpha1.Resources, out *namedresources.Resources, s conversion.Scope) error {
	out.Instances = *(*[]namedresources.Instance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_v1alpha1_Resources_To_namedresources_Resources is an autogenerated conversion function.
func Convert_v1alpha1_Resources_To_namedresources_Resources(in *v1alpha1.Resources, out *namedresources.Resources, s conversion.Scope) error {
	return autoConvert_v1alpha1_Resources_To_namedresources_Resources(in, out, s)
}

func autoConvert_namedresources_Resources_To_v1alpha1_Resources(in *namedresources.Resources, out *v1alpha1.Resources, s conversion.Scope) error {
	out.Instances = *(*[]v1alpha1.Instance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_namedresources_Resources_To_v1alpha1_Resources is an autogenerated conversion function.
func Convert_namedresources_Resources_To_v1alpha1_Resources(in *namedresources.Resources, out *v1alpha1.Resources, s conversion.Scope) error {
	return autoConvert_namedresources_Resources_To_v1alpha1_Resources(in, out, s)
}

func autoConvert_v1alpha1_StringSlice_To_namedresources_StringSlice(in *v1alpha1.StringSlice, out *namedresources.StringSlice, s conversion.Scope) error {
	out.Strings = *(*[]string)(unsafe.Pointer(&in.Strings))
	return nil
}

// Convert_v1alpha1_StringSlice_To_namedresources_StringSlice is an autogenerated conversion function.
func Convert_v1alpha1_StringSlice_To_namedresources_StringSlice(in *v1alpha1.StringSlice, out *namedresources.StringSlice, s conversion.Scope) error {
	return autoConvert_v1alpha1_StringSlice_To_namedresources_StringSlice(in, out, s)
}

func autoConvert_namedresources_StringSlice_To_v1alpha1_StringSlice(in *namedresources.StringSlice, out *v1alpha1.StringSlice, s conversion.Scope) error {
	out.Strings = *(*[]string)(unsafe.Pointer(&in.Strings))
	return nil
}

// Convert_namedresources_StringSlice_To_v1alpha1_StringSlice is an autogenerated conversion function.
func Convert_namedresources_StringSlice_To_v1alpha1_StringSlice(in *namedresources.StringSlice, out *v1alpha1.StringSlice, s conversion.Scope) error {
	return autoConvert_namedresources_StringSlice_To_v1alpha1_StringSlice(in, out, s)
}
