/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// NodeResourceInstanceApplyConfiguration represents an declarative configuration of the NodeResourceInstance type for use
// with apply.
type NodeResourceInstanceApplyConfiguration struct {
	ID         *string               `json:"id,omitempty"`
	APIVersion *string               `json:"apiVersion,omitempty"`
	Kind       *string               `json:"kind,omitempty"`
	Data       *runtime.RawExtension `json:"data,omitempty"`
}

// NodeResourceInstanceApplyConfiguration constructs an declarative configuration of the NodeResourceInstance type for use with
// apply.
func NodeResourceInstance() *NodeResourceInstanceApplyConfiguration {
	return &NodeResourceInstanceApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *NodeResourceInstanceApplyConfiguration) WithID(value string) *NodeResourceInstanceApplyConfiguration {
	b.ID = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *NodeResourceInstanceApplyConfiguration) WithAPIVersion(value string) *NodeResourceInstanceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *NodeResourceInstanceApplyConfiguration) WithKind(value string) *NodeResourceInstanceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithData sets the Data field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Data field is set to the value of the last call.
func (b *NodeResourceInstanceApplyConfiguration) WithData(value runtime.RawExtension) *NodeResourceInstanceApplyConfiguration {
	b.Data = &value
	return b
}
