/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "k8s.io/api/storage/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CSIStoragePoolLister helps list CSIStoragePools.
type CSIStoragePoolLister interface {
	// List lists all CSIStoragePools in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.CSIStoragePool, err error)
	// Get retrieves the CSIStoragePool from the index for a given name.
	Get(name string) (*v1alpha1.CSIStoragePool, error)
	CSIStoragePoolListerExpansion
}

// cSIStoragePoolLister implements the CSIStoragePoolLister interface.
type cSIStoragePoolLister struct {
	indexer cache.Indexer
}

// NewCSIStoragePoolLister returns a new CSIStoragePoolLister.
func NewCSIStoragePoolLister(indexer cache.Indexer) CSIStoragePoolLister {
	return &cSIStoragePoolLister{indexer: indexer}
}

// List lists all CSIStoragePools in the indexer.
func (s *cSIStoragePoolLister) List(selector labels.Selector) (ret []*v1alpha1.CSIStoragePool, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CSIStoragePool))
	})
	return ret, err
}

// Get retrieves the CSIStoragePool from the index for a given name.
func (s *cSIStoragePoolLister) Get(name string) (*v1alpha1.CSIStoragePool, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("csistoragepool"), name)
	}
	return obj.(*v1alpha1.CSIStoragePool), nil
}
