/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha2 "k8s.io/api/resource/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	resourcev1alpha2 "k8s.io/client-go/applyconfigurations/resource/v1alpha2"
	scheme "k8s.io/client-go/kubernetes/scheme"
	rest "k8s.io/client-go/rest"
)

// NodeResourceCapacitiesGetter has a method to return a NodeResourceCapacityInterface.
// A group's client should implement this interface.
type NodeResourceCapacitiesGetter interface {
	NodeResourceCapacities() NodeResourceCapacityInterface
}

// NodeResourceCapacityInterface has methods to work with NodeResourceCapacity resources.
type NodeResourceCapacityInterface interface {
	Create(ctx context.Context, nodeResourceCapacity *v1alpha2.NodeResourceCapacity, opts v1.CreateOptions) (*v1alpha2.NodeResourceCapacity, error)
	Update(ctx context.Context, nodeResourceCapacity *v1alpha2.NodeResourceCapacity, opts v1.UpdateOptions) (*v1alpha2.NodeResourceCapacity, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.NodeResourceCapacity, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.NodeResourceCapacityList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.NodeResourceCapacity, err error)
	Apply(ctx context.Context, nodeResourceCapacity *resourcev1alpha2.NodeResourceCapacityApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.NodeResourceCapacity, err error)
	NodeResourceCapacityExpansion
}

// nodeResourceCapacities implements NodeResourceCapacityInterface
type nodeResourceCapacities struct {
	client rest.Interface
}

// newNodeResourceCapacities returns a NodeResourceCapacities
func newNodeResourceCapacities(c *ResourceV1alpha2Client) *nodeResourceCapacities {
	return &nodeResourceCapacities{
		client: c.RESTClient(),
	}
}

// Get takes name of the nodeResourceCapacity, and returns the corresponding nodeResourceCapacity object, and an error if there is any.
func (c *nodeResourceCapacities) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	result = &v1alpha2.NodeResourceCapacity{}
	err = c.client.Get().
		Resource("noderesourcecapacities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeResourceCapacities that match those selectors.
func (c *nodeResourceCapacities) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.NodeResourceCapacityList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.NodeResourceCapacityList{}
	err = c.client.Get().
		Resource("noderesourcecapacities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeResourceCapacities.
func (c *nodeResourceCapacities) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("noderesourcecapacities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeResourceCapacity and creates it.  Returns the server's representation of the nodeResourceCapacity, and an error, if there is any.
func (c *nodeResourceCapacities) Create(ctx context.Context, nodeResourceCapacity *v1alpha2.NodeResourceCapacity, opts v1.CreateOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	result = &v1alpha2.NodeResourceCapacity{}
	err = c.client.Post().
		Resource("noderesourcecapacities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeResourceCapacity).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeResourceCapacity and updates it. Returns the server's representation of the nodeResourceCapacity, and an error, if there is any.
func (c *nodeResourceCapacities) Update(ctx context.Context, nodeResourceCapacity *v1alpha2.NodeResourceCapacity, opts v1.UpdateOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	result = &v1alpha2.NodeResourceCapacity{}
	err = c.client.Put().
		Resource("noderesourcecapacities").
		Name(nodeResourceCapacity.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeResourceCapacity).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeResourceCapacity and deletes it. Returns an error if one occurs.
func (c *nodeResourceCapacities) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("noderesourcecapacities").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeResourceCapacities) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("noderesourcecapacities").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeResourceCapacity.
func (c *nodeResourceCapacities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.NodeResourceCapacity, err error) {
	result = &v1alpha2.NodeResourceCapacity{}
	err = c.client.Patch(pt).
		Resource("noderesourcecapacities").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeResourceCapacity.
func (c *nodeResourceCapacities) Apply(ctx context.Context, nodeResourceCapacity *resourcev1alpha2.NodeResourceCapacityApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.NodeResourceCapacity, err error) {
	if nodeResourceCapacity == nil {
		return nil, fmt.Errorf("nodeResourceCapacity provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(nodeResourceCapacity)
	if err != nil {
		return nil, err
	}
	name := nodeResourceCapacity.Name
	if name == nil {
		return nil, fmt.Errorf("nodeResourceCapacity.Name must be provided to Apply")
	}
	result = &v1alpha2.NodeResourceCapacity{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("noderesourcecapacities").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
